version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes --requirepass 123456
    volumes:
      - ./redis/data:/data
    ports:
      - 6318:6379
    networks:
      - mvp_network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: mvp
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mvp
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3318:3306
    networks:
      - mvp_network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8018:8018
    networks:
      - mvp_network

  app1:
    image: mvp-server:latest
    env_file:
      - ./app.env
    environment:
      APP_NAME: app1
    ports:
      - 5118:5018
    depends_on:
      - mysql
      - redis
    networks:
      - mvp_network

  app2:
    image: mvp-server:latest
    env_file:
      - ./app.env
    environment:
      APP_NAME: app2
    ports:
      - 5218:5018
    depends_on:
      - mysql
      - redis
    networks:
      - mvp_network

  app3:
    image: mvp-server:latest
    env_file:
      - ./app.env
    environment:
      APP_NAME: app3
    ports:
      - 5318:5018
    depends_on:
      - mysql
      - redis
    networks:
      - mvp_network

  app4:
    image: mvp-server:latest
    env_file:
      - ./app.env
    environment:
      APP_NAME: app4
    ports:
      - 5418:5018
    depends_on:
      - mysql
      - redis
    networks:
      - mvp_network

networks:
  mvp_network:
    driver: bridge
